GameStop/urls.py
from django.contrib import admin
from django.urls import path,include
from Product.views import home_view
from Product.views import contact_page
from Product.views import about_page
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('product/',include('Product.urls',namespace='product')),
    path('',home_view,name='home'),
    path('contact/',contact_page,name='contact'),
    path('product/', include('django.contrib.auth.urls')),
    path('admin/',admin.site.urls),
    path('about/',about_page,name='about'),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Product/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views

from .views import (
    product_create_view,
    product_delete_view,
    product_list_view,
    product_detail_view,
    cart_add,
    cart_detail,
    cart_remove,
    order_create,
    search_list,
)

app_name="Product"
urlpatterns=[
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('create/',product_create_view,name='create'),
    path('<int:id>/delete/',product_delete_view,name='delete'),
    path('',product_list_view,name='list'),
    path('<int:id>',product_detail_view,name='product-detail'),
    path('cart/',cart_detail,name='cart-detail'),
    path('cart/add/<int:id>', cart_add,name='cart-add'),
    path('cart/remove/<int:id>', cart_remove,name='cart-remove'),
    path('order/create/',order_create,name='order_create'),
    path('search/',search_list,name='search'),
]

Product/models.py
from django.db import models
from django.urls import reverse
import os
import random

# Create your models here.



class Product(models.Model):


    name=models.CharField(max_length=120)
    description=models.TextField(default=True)
    price=models.DecimalField(max_digits=10, decimal_places=2)
    slug = models.SlugField(max_length=100, db_index=True)
    image = models.ImageField(upload_to='Product/', null=True, blank=True)
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)



    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Product:product-detail",kwargs={"id":self.id})

class Order(models.Model):
        first_name = models.CharField(max_length=60)
        last_name = models.CharField(max_length=60)
        email = models.EmailField()
        address = models.CharField(max_length=150)
        postal_code = models.CharField(max_length=30)
        city = models.CharField(max_length=100)
        created = models.DateTimeField(auto_now_add=True)
        updated = models.DateTimeField(auto_now=True)
        paid = models.BooleanField(default=False)

        class Meta:
            ordering = ('-created',)

        def __str__(self):
            return 'Order {}'.format(self.id)

        def get_total_cost(self):
            return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

Product/forms.py
from django import forms
from .models import Product,Order
from django.contrib.auth import get_user_model





class ProductForm(forms.ModelForm):
    class Meta:
        model=Product
        fields=[
            'name',
            'description',
            'price'

              ]




User = get_user_model()

class ContactForm(forms.Form):
    fullname = forms.CharField(
            widget=forms.TextInput(
                    attrs={
                        "class": "form-control",
                        "placeholder": "Your full name"
                    }
                    )
            )
    email    = forms.EmailField(
            widget=forms.EmailInput(
                    attrs={
                        "class": "form-control",
                        "placeholder": "Your email"
                    }
                    )
            )
    content  = forms.CharField(
            widget=forms.Textarea(
                attrs={
                    'class': 'form-control',
                    "placeholder": "Your message"
                    }
                )
            )





PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address', 'postal_code', 'city']

Product/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Product
from .forms import ProductForm
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from .forms import ContactForm
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from .cart import Cart
from .forms import CartAddProductForm
from .models import OrderItem
from .forms import OrderCreateForm
# Create your views here.
def home_view(request,*args,**kwargs):
    return render(request,'home.html',{})


def product_create_view(request):
    form=ProductForm(request.POST or None)
    if form.is_valid():
        form.save()
        form=ProductForm()
    context={
        'form':form
    }
    return render(request,"product/product_create.html",context)

def product_delete_view(request,id):
    obj=get_object_or_404(Product, id=id)
    if request.method=='POST':
        obj.delete()
        redirect('../../')
    context={
        'object':obj
    }
    return render(request,'product/product_delete.html',context)

def product_list_view(request):
    queryset=Product.objects.all()
    context={
        'object_list':queryset
    }
    return render(request,'product/product_list.html',context)


def product_detail_view(request,id):
    obj=get_object_or_404(Product,id=id)
    cart_product_form = CartAddProductForm()
    context={
        'object':obj,
        'cart_product_form': cart_product_form
    }
    return render(request,'product/product_detail.html', context)




class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

def contact_page(request):
        contact_form = ContactForm(request.POST or None)
        context = {
            "title": "Contact",
            "content": " Welcome to the contact page.",
            "form": contact_form,
        }
        if contact_form.is_valid():
            print(contact_form.cleaned_data)
            if request.is_ajax():
                return JsonResponse({"message": "Thank you for your submission"})

        if contact_form.errors:
            errors = contact_form.errors.as_json()
            if request.is_ajax():
                return HttpResponse(errors, status=400, content_type='application/json')

        # if request.method == "POST":
        #     #print(request.POST)
        #     print(request.POST.get('fullname'))
        #     print(request.POST.get('email'))
        #     print(request.POST.get('content'))
        return render(request, "contact/view.html", context)
def about_page(request):
    context = {
        "title":"About Page",
        "content":" Welcome to the about page."
    }
    return render(request, "about.html", context)


@require_POST
def cart_add(request,id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('Product:cart-detail')


def cart_remove(request, id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=id)
    cart.remove(product)
    return redirect('Product:cart-detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(
                    order=order,
                    product=item['product'],
                    price=item['price'],
                    quantity=item['quantity']
                )
            cart.clear()
        return render(request, 'order/created.html', {'order': order})
    else:
        form = OrderCreateForm()
    return render(request, 'order/create.html', {'form': form})


def search_list(request):
    object_list = Product.objects.all()
    query = request.GET.get("q")
    if query:
        object_list = object_list.filter(name__icontains=query)

        return render(request, 'product/product_list.html', {'object_list': object_list})

Product/templates/cart/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart
{% endblock %}
 
 
{% block content %}

    <div class="container">
        <div class="row" style="margin-top: 6%">
        <h2>Your Shopping Cart
            <span class="badge pull-right">
                {% with totail_items=cart|length %}
                    {% if cart|length > 0 %}
                        My Shopping Order:
                        <a href="{% url "Product:cart-detail" %}" style="color: #ffffff">
                            {{ totail_items }} item {{ totail_items|pluralize }},{{ cart.get_total_price }}
                        </a>
                        {% else %}
                        Your cart is empty.
                    {% endif %}
                {% endwith %}
            </span>
        </h2>
            <table class="table table-striped table-hover">
                <thead style="background-color: #5AC8FA">
                    <tr>
                        <th>Image</th>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Remove</th>
                        <th>Unit Price</th>
                        <th>Price</th>
                    </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    {% with product=item.product  %}
                        <tr>
                            <td>
                                <a href="{{ product.get__absolute_url }}">
                                    <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 130px; width: auto">
                                </a>
                            </td>
                            <td>{{ product.name }}</td>
                            <td>
                                <form action="{% url "Product:cart-add" product.id %}" method="post">
                                    {% csrf_token %}
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.update }}
                                    <input type="submit" value="Update" class="btn btn-info">
                                </form>
                            </td>
                            <td>
                                <a href="{% url "Product:cart-remove" product.id %}">Remove</a>
                            </td>
                            <td> {{ item.price }}</td>
                            <td> {{ item.total_price }}</td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr style="background-color: #5AC8FA">
                    <td><b>Total</b></td>
                    <td colspan="4"></td>
                    <td colspan="num"><b> {{ cart.get_total_price }}</b></td>
                </tr>
                </tbody>
            </table>
        <p class="text-right">
            <a href="{% url "Product:list" %}" class="btn btn-default">Continue Shopping</a>
            <a href="{% url "Product:order_create" %}" class="btn btn-primary">Checkout</a>
        </p>
        </div>
    </div>
{% endblock %}