GameStop/urls.py
from django.contrib import admin
from django.urls import path,include
from Product.views import home_view
from Product.views import contact_page
from Product.views import about_page
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('product/',include('Product.urls',namespace='product')),
    path('',home_view,name='home'),
    path('contact/',contact_page,name='contact'),
    path('product/', include('django.contrib.auth.urls')),
    path('admin/',admin.site.urls),
    path('about/',about_page,name='about'),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Product/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views

from .views import (
    product_create_view,
    product_delete_view,
    product_list_view,
    product_detail_view,
    cart_add,
    cart_detail,
    cart_remove,
    order_create,
    search_list,
)

app_name="Product"
urlpatterns=[
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('create/',product_create_view,name='create'),
    path('<int:id>/delete/',product_delete_view,name='delete'),
    path('',product_list_view,name='list'),
    path('<int:id>',product_detail_view,name='product-detail'),
    path('cart/',cart_detail,name='cart-detail'),
    path('cart/add/<int:id>', cart_add,name='cart-add'),
    path('cart/remove/<int:id>', cart_remove,name='cart-remove'),
    path('order/create/',order_create,name='order_create'),
    path('search/',search_list,name='search'),
]

Product/models.py
from django.db import models
from django.urls import reverse
import os
import random

# Create your models here.



class Product(models.Model):


    name=models.CharField(max_length=120)
    description=models.TextField(default=True)
    price=models.DecimalField(max_digits=10, decimal_places=2)
    slug = models.SlugField(max_length=100, db_index=True)
    image = models.ImageField(upload_to='Product/', null=True, blank=True)
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)



    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Product:product-detail",kwargs={"id":self.id})

class Order(models.Model):
        first_name = models.CharField(max_length=60)
        last_name = models.CharField(max_length=60)
        email = models.EmailField()
        address = models.CharField(max_length=150)
        postal_code = models.CharField(max_length=30)
        city = models.CharField(max_length=100)
        created = models.DateTimeField(auto_now_add=True)
        updated = models.DateTimeField(auto_now=True)
        paid = models.BooleanField(default=False)

        class Meta:
            ordering = ('-created',)

        def __str__(self):
            return 'Order {}'.format(self.id)

        def get_total_cost(self):
            return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

Product/forms.py
from django import forms
from .models import Product,Order
from django.contrib.auth import get_user_model





class ProductForm(forms.ModelForm):
    class Meta:
        model=Product
        fields=[
            'name',
            'description',
            'price'

              ]




User = get_user_model()

class ContactForm(forms.Form):
    fullname = forms.CharField(
            widget=forms.TextInput(
                    attrs={
                        "class": "form-control",
                        "placeholder": "Your full name"
                    }
                    )
            )
    email    = forms.EmailField(
            widget=forms.EmailInput(
                    attrs={
                        "class": "form-control",
                        "placeholder": "Your email"
                    }
                    )
            )
    content  = forms.CharField(
            widget=forms.Textarea(
                attrs={
                    'class': 'form-control',
                    "placeholder": "Your message"
                    }
                )
            )





PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address', 'postal_code', 'city']

Product/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Product
from .forms import ProductForm
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from .forms import ContactForm
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from .cart import Cart
from .forms import CartAddProductForm
from .models import OrderItem
from .forms import OrderCreateForm
# Create your views here.
def home_view(request,*args,**kwargs):
    return render(request,'home.html',{})


def product_create_view(request):
    form=ProductForm(request.POST or None)
    if form.is_valid():
        form.save()
        form=ProductForm()
    context={
        'form':form
    }
    return render(request,"product/product_create.html",context)

def product_delete_view(request,id):
    obj=get_object_or_404(Product, id=id)
    if request.method=='POST':
        obj.delete()
        redirect('../../')
    context={
        'object':obj
    }
    return render(request,'product/product_delete.html',context)

def product_list_view(request):
    queryset=Product.objects.all()
    context={
        'object_list':queryset
    }
    return render(request,'product/product_list.html',context)


def product_detail_view(request,id):
    obj=get_object_or_404(Product,id=id)
    cart_product_form = CartAddProductForm()
    context={
        'object':obj,
        'cart_product_form': cart_product_form
    }
    return render(request,'product/product_detail.html', context)




class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

def contact_page(request):
        contact_form = ContactForm(request.POST or None)
        context = {
            "title": "Contact",
            "content": " Welcome to the contact page.",
            "form": contact_form,
        }
        if contact_form.is_valid():
            print(contact_form.cleaned_data)
            if request.is_ajax():
                return JsonResponse({"message": "Thank you for your submission"})

        if contact_form.errors:
            errors = contact_form.errors.as_json()
            if request.is_ajax():
                return HttpResponse(errors, status=400, content_type='application/json')

        # if request.method == "POST":
        #     #print(request.POST)
        #     print(request.POST.get('fullname'))
        #     print(request.POST.get('email'))
        #     print(request.POST.get('content'))
        return render(request, "contact/view.html", context)
def about_page(request):
    context = {
        "title":"About Page",
        "content":" Welcome to the about page."
    }
    return render(request, "about.html", context)


@require_POST
def cart_add(request,id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('Product:cart-detail')


def cart_remove(request, id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=id)
    cart.remove(product)
    return redirect('Product:cart-detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(
                    order=order,
                    product=item['product'],
                    price=item['price'],
                    quantity=item['quantity']
                )
            cart.clear()
        return render(request, 'order/created.html', {'order': order})
    else:
        form = OrderCreateForm()
    return render(request, 'order/create.html', {'form': form})


def search_list(request):
    object_list = Product.objects.all()
    query = request.GET.get("q")
    if query:
        object_list = object_list.filter(name__icontains=query)

        return render(request, 'product/product_list.html', {'object_list': object_list})

Product/templates/about.html
{% extends "base.html" %}



{% block content %}

<div class='row'>
<div class='col-sm-6 col-sm-offset-3'>
<h1>About Us</h1>
<p>We are an American video game, consumer electronics, and wireless services retailer.[2] Our company is headquartered in Grapevine, Texas, United States, a suburb of Dallas, and operates 7,117 retail stores throughout the United States, Canada, Australia, New Zealand, and Europe. Our retail stores primarily operate under the GameStop, EB Games, ThinkGeek, and Micromania brands.[2]</p>
    <h2>Other Brands:-</h2>

    <h3>1)Game Informer</h3>
    <p>Game Informer is a magazine owned by GameStop, Inc. and primarily sold through subscriptions which can be purchased at GameStop locations.[55] Purchasing a subscription to the magazine also gets the subscriber the PowerUp Rewards Pro card, a premium version of GameStop's loyalty card. This increases all store-credit trade values by 10%, discounts all used accessories and games by 10%, gives new PowerUp members a coupon for "Buy 2 Get 1 Free" on pre-owned games and accessories, enters them twice for the Epic Rewards Giveaway for each purchase, gives the cardholder opportunities to gain points with their purchases, and redeem them for rewards and gains them access to special content on the Game Informer website.</p>

    <h3>2)GameStop PC</h3>
    <p>GameStop PC Downloads, formerly called Impulse, is a digital distribution service run and operated by GameStop. Originally known as Impulse when owned by Stardock, it was sold to GameStop in 2011 and rebranded as GameStop PC Downloads, with the Impulse client renamed as the GameStop App. Under the ownership of GameStop, the service has had a redesign and sells games that use other platforms such as Steam while also selling games that use its own proprietary DRM solution Impulse:Reactor.</p>

</div>

</div>


{% endblock %}

Product/templates/base.html
{% load static %}
<!DOCTYPE html>
    <html lang="en">
    <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'Product/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->

      <title>{% block head_title %}Base Template{% endblock %}</title>
        {%  block search %}{%  endblock %}
        {% include 'base/css.html' %}
        <style>
           .topright {

               position: absolute;
               top: 80px;
               right: 16px;
               font-size: 18px;
           }
            .topright1 {

                position: absolute;
                top: 80px;
                right: 400px;
                font-size: 18px;
            }
           .h1 {text-align:center;}
           .center {
     display: block;
    margin-left: auto;
    margin-right: auto;
    width: 50%;
}




        </style>
    </head>

    <body>
      {% include 'base/navbar.html' with brand_name='GameStop' %}
        <div class="body1">
      <div class='container'>
        {% if messages %}
      <div class="alert alert-success messages">
          {% for message in messages %}
          <span{% if message.tags %} class="{{ message.tags }}"{% endif %}>
              {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
              {{ message }}<br/>
          </span>
          {% endfor %}
      </div>
      {% endif %}
      </div>
      <div class="container">
    <div class="row" style="margin-top: 6%">
        <div class="topright">
         <button class="btn btn-info pull-right">
            {% with totail_items=cart|length %}
                {% if cart|length > 0 %}
                    My Shopping Order:
                    <a href="{% url "Product:cart-detail" %}" style="color: #ffffff">
                        {{ totail_items }} item {{ totail_items|pluralize }},{{ cart.get_total_price }}$
                    </a>
                    {% else %}
                    Your cart is empty.
                {% endif %}
            {% endwith %}
         </button>
        </div>
    </div>
</div>
        </div>
      {% block jumbotron %}{% endblock %}
       {% block nik %}{% endblock %}
      <div class="container">{% block content %}

            {% endblock %}</div>

        {% include 'base/js.html' %}
        {% block javascript %}

        {% endblock %}
    </body>
  </html>

Product/templates/home.html
{% extends "base.html" %}
{% load static %}

<title>{% block head_title %}Home Page Template{% endblock %}</title>
{% block search %}

    <div class="topright1">
    <form method='GET' action='{% url 'product:search' %}' style="margin:auto;max-width:300px">
    <input type='text' style="width: 150px; height: 30px" name='q' placeholder='Search Games' value="{{request.GET.q}}"/>
    <input type = 'submit' class='btn btn-info pull right' value = 'search'/></form>
    </div>

{% endblock %}



{% block nik %}

{% endblock %}
{% block jumbotron %}

                <div class="container-fluid">

                    <div class="row">
                        <div class="col-lg-3">

          <h1 class="my-4"><img src="{% static 'Product/img/GameStop.jpg' %}" class="img-responsive" height="172" width="272"></h1>
          <div class="list-group">
            <a href="{%  url 'product:list' %}" class="list-group-item">Newly Released</a>
            <a href="{%  url 'product:list' %}"class="list-group-item">Popular Games</a>
            <a href="{%  url 'product:list' %}" class="list-group-item">Used Games</a>
          </div>

        </div
                            <div class="col-lg-9">

          <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
            <ol class="carousel-indicators">
              <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
              <div class="carousel-item active">
                <img class="d-block-img-fluid" src="{% static 'Product/img/deal1.png' %}" style="width:900px;height:350px" alt="First slide">
              </div>
              <div class="carousel-item">
                <img class="d-block img-fluid" src="{% static 'Product/img/PUBG1.jpg' %}" style="width:900px;height:350px" alt="Second slide">
              </div>
              <div class="carousel-item">
                <img class="d-block img-fluid" src="{% static 'Product/img/FIFA19.jpg' %}" style="width:900px;height:350px" alt="Third slide">
              </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>




          <div class="row">

            <div class="col-lg-3 col-md-6 mb-4">
              <div class="card h-100">
                <a href="#"><img class="card-img-top" src="{% static 'Product/img/pubg.jpg' %}"alt=""></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="http://127.0.0.1:8000/product/1">Game of the month</a>
                  </h4>

                  <p class="card-text">PlayerUnknown's Battlegrounds (PUBG) is an online multiplayer battle royale game developed and published by ..</p>
                </div>
                <div class="card-footer">
                  <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                </div>
              </div>
            </div>

            <div class="col-lg-3 col-md-6 mb-4">
              <div class="card h-100">
                <a href="#"><img class="card-img-top" src="{% static 'Product/img/Fortnite.jpg' %}" alt=""></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="http://127.0.0.1:8000/product/2">Most popular Game</a>
                  </h4>

                  <p class="card-text">Fortnite is an online video game created in 2017, developed by Epic Games, and ...</p>
                </div>
                <div class="card-footer">
                  <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                </div>
              </div>
            </div>

            <div class="col-lg-3 col-md-6 mb-4">
              <div class="card h-100">
                <a href=""><img class="card-img-top" src="{% static 'Product/img/headphones.jpg' %}" alt=""></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="http://127.0.0.1:8000/product/8">Game Related Item on Sale</a>
                  </h4>

                  <p class="card-text">Gaming Headphones</p>
                </div>
                <div class="card-footer">
                  <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                </div>
              </div>
            </div>

            <div class="col-lg-3 col-md-6 mb-4">
              <div class="card h-100">
                <a href="#"><img class="card-img-top" src="{% static 'Product/img/dota-2-logo.0.jpg' %}" alt=""></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="http://127.0.0.1:8000/product/3">Bestseller</a>
                  </h4>

                  <p class="card-text">Dota 2 is a free-to-play multiplayer online battle arena (MOBA) video game developed and ...</p>
                </div>
                <div class="card-footer">
                  <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                </div>
              </div>
            </div>





          </div>
          <!-- /.row -->

        </div>
        <!-- /.col-lg-9 -->

      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->






	{% endblock %}

Product/templates/signup.html
{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'Product/style.css' %}">
  <h2>Sign up</h2>
      <div class="login-page">
  <div class="form">
      <form method="post" class=""register-form">
  <
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}

        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
  </div></div>
{% endblock %}